### ISSUE TITLE
Unavailable status

### ISSUE THREAD

**Issue by AlbertHakvoort** [robbinjanssen/home-assistant-omnik-inverter#139]
Is it possible to prevent the unavailable status in Home Assistant, so when the connection is lost to the inverter, the last known values are showed

![image](https://user-images.githubusercontent.com/23001971/201960326-e6b4f1cf-a969-4252-8dbe-ef80ba6074f9.png)

**Comment by MarijnS95** [comment]
This is however the right value to propagate when it comes to how HASS stores these values in the `states` table and in the short/long-term statistics table.

I recommend using cards that base their values on statistics rather than the raw entity states (even if these are only updated every hour) or look for cards / template values that display the last known state for an entity instead of the most recent unknown value.

**Comment by robbinjanssen** [comment]
Hi @AlbertHakvoort, this could be fixed by adding an (optional) caching layer. We have an issue for this already, this is a duplicate of https://github.com/robbinjanssen/home-assistant-omnik-inverter/issues/51
