### ISSUE TITLE
New devices and entities generated after upgrade.

### ISSUE THREAD

**Issue by ronaldt80** [robbinjanssen/home-assistant-omnik-inverter#153]
Upgrade to v 2.5 results in new entity IDs being created wrecking the energy dashboard history.

Following the upgrade to the new version my old entities were listed unavailable with new entities being created. This breaks historic data in the energy dashboard. When i changed the names all history was gone. Now rolled back to yesterday's backup to restore data.

Could someone please advise how to perform the upgrade without this impact?

## Diagnostics

```json
"Copy here the code or upload the file"
```

**Comment by robbinjanssen** [comment]
Did you come from version v2.4.x? or an earlier version?

**Comment by robbinjanssen** [comment]
I think this has to do because i've used another unique_Id, i though they were similar:
v2.4.2:
https://github.com/robbinjanssen/home-assistant-omnik-inverter/blob/v2.4.2/custom_components/omnik_inverter/sensor.py#L221

v2.5.0
https://github.com/robbinjanssen/home-assistant-omnik-inverter/blob/main/custom_components/omnik_inverter/sensor.py#L242


The name however is the same

**Comment by robbinjanssen** [comment]
@ronaldt80 Try v2.5.1 :)

**Comment by ronaldt80** [comment]
Perfect! This works - many thanks for the quick follow up
